source("../fitting_function.R")

run_model_fit(predictors = c("food", "housing", "health", "security_obj", "social_support", "education", "occupation", "personal_income", "relative_income", "country_average_food", "country_average_housing", "country_average_health", "country_average_security_obj", "country_average_social_support", "country_average_education", "country_average_occupation", "gdp", "growth", "government_effectiveness", "democracy", "social_protection"),
              outcome = "confidence_institutions",
              drop_na_variables = c("food",
                             "housing",
                             "health",
                             "water",
                             "air",
                             "healthcare",
                             "security",
                             "social_support",
                             "respect",
                             "education",
                             "interesting_activity",
                             "recreation",
                             "occupation",
                             "freedom",
                             "personal_income",
                             "relative_income",
                             "country_average_food",
                             "country_average_housing",
                             "country_average_health",
                             "country_average_water",
                             "country_average_air",
                             "country_average_healthcare",
                             "country_average_security",
                             "country_average_social_support",
                             "country_average_respect",
                             "country_average_education",
                             "country_average_interesting_activity",
                             "country_average_recreation",
                             "country_average_occupation",
                             "country_average_freedom",
                             "gdp",
                             "growth",
                             "government_effectiveness",
                             "democracy",
                             "social_protection"),
              suffix_output_files = "med")

run_model_fit(predictors = c("food", "housing", "health", "security_obj", "social_support", "education", "occupation", "personal_income", "relative_income", "confidence_institutions", "country_average_food", "country_average_housing", "country_average_health", "country_average_security_obj", "country_average_social_support", "country_average_education", "country_average_occupation", "gdp", "growth", "government_effectiveness", "democracy", "social_protection"),
              drop_na_variables = c("food",
                             "housing",
                             "health",
                             "water",
                             "air",
                             "healthcare",
                             "security",
                             "social_support",
                             "respect",
                             "education",
                             "interesting_activity",
                             "recreation",
                             "occupation",
                             "freedom",
                             "personal_income",
                             "relative_income",
                             "country_average_food",
                             "country_average_housing",
                             "country_average_health",
                             "country_average_water",
                             "country_average_air",
                             "country_average_healthcare",
                             "country_average_security",
                             "country_average_social_support",
                             "country_average_respect",
                             "country_average_education",
                             "country_average_interesting_activity",
                             "country_average_recreation",
                             "country_average_occupation",
                             "country_average_freedom",
                             "gdp",
                             "growth",
                             "government_effectiveness",
                             "democracy",
                             "social_protection"),
              suffix_output_files = "out")
